version: 2
jobs:
  apks:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build docker SDK image
          command: docker build -t apks -f Dockerfile .
      - run:
          name: Build black
          command: docker run --rm apks /bin/sh -c 'cd black && ./build.sh'
      - run:
          name: Build frame
          command: docker run --rm apks /bin/sh -c 'cd frame && ./build.sh'
      - run:
          name: Build setup
          command: docker run --rm apks /bin/sh -c 'cd setup && ./build.sh'
      - run:
          name: Build offroad
          command: docker run --rm apks /bin/sh -c 'cd offroad && ./build.sh'

workflows:
  version: 2
  main:
    jobs:
      - apks
    
